### PR TITLE
Use Cypress for end-to-end tests

### PR DESCRIPTION
**Pull request by emilvirkki**
Puppeteer was a lot better than WebdriverIO, but Cypress seems even nicer. This PR updates the existing smoke test from Puppeteer to Cypress.

This PR also adds a bit of documentation about running the tests locally.

### CODE REVIEW

**Comment by googol** [comment]
Try out start-server-and-test  for that last bullet point

**Comment by supertassu** [comment]
Does Cypress require a browser driver (such as Chromedriver)? If so, can you add that to documentation?

**Comment by emilvirkki** [comment]
> Does Cypress require a browser driver (such as Chromedriver)? If so, can you add that to documentation?

I think all the necessary components should come with the cypress npm package, at least I didn't install anything else. Would of course be good to test manually that the tests work locally without installing anything extra :)

**Comment by googol** [comment]
The npm package installs all the necessary native dependencies

**Comment by googol** [comment]
Closing in favor of https://github.com/partio-scout/reki/pull/273 which includes this

**Pull request closed without merging**
